[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "threat-thinker"
version = "0.1.0"
description = "A toolkit for automated threat modeling"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "Apache 2.0" }
dependencies = []

[project.scripts]
threat-thinker = "main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]